version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: 'python'
    command: '-m flask run --host=0.0.0.0'
    env_file: 
      - .env
    volumes:
      - ./:/usr/src/app
