version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: 'python'
    command: uwsgi --emperor /usr/src/app
    env_file: 
      - .env
    volumes:
      - ./:/usr/src/app
