name: {{env.CI_PROJECT_NAME}}
targetPort: 5000
memory: 200M
cpu: 0.1

profiles:
  production:
    domains:
      - {{env.CI_PROJECT_NAME}}.k.elnino-production.com
    namespace: production
  acceptance:
    domains:
      - {{env.CI_PROJECT_NAME}}.k.elnino-acceptance.com
    namespace: acceptance
  dev:
    domains:
      - {{env.CI_PROJECT_NAME}}.k.elnino-dev.com
    namespace: dev

containers:
  - dockerfile: Dockerfile
    context: .
